### PR TITLE
Version next

### PR DESCRIPTION
**Pull request by arobson**
This would introduce fount 0.2.0:
* bug fix - inject and resolve across multiple containers now works correctly
* improvement - functions that can't be resolved in static or scoped lifecycles immediately will be once all dependencies become available
* feature - add a way to register function as value without a wrapper
* NPM modules
 	* don't auto-backfill dependencies from NPM anymore, it's kinda gross
 	* provide ability to grab an "ambient" module from the require cache

### CODE REVIEW

**Comment by calvinb** [comment]
@arobson Do you remember this PR? It's been a minute. This is looking great so far, but I have a concern about the versioning. The bit about no longer backfilling missing dependencies from npm is a breaking change. It breaks core-leankit-api. Fixing it is not hard, but I think this change needs a major version bump, which of course would take it to 1.0.0. How you normally handling a breaking change to a pre-1.0 library?

**Comment by arobson** [comment]
@calvinb - the practice (which is technically incorrect) in pre-1.0.0 libs was to treat 0.x.0 changes as breaking. I'd be fine with this going to a 1.0.0 release if that's ok with others. It looks like I'd need to change the PR anyway because of what I have in `package.json` anyway. Let me know how I should change this and I'll update the `CHANGELOG` as well and get this lined up.

**Comment by calvinb** [comment]
@arobson TIL how pre-1.0.0 caret references are handled. In light of that, I think this version change is fine. Is there anything else you want to tweak, or is it ready to merge?

**Comment by arobson** [comment]
@calvinb I did change the package.json because I still had a pre-release in the version field. It should be ok to merge and publish now. Thanks 😃

**Pull request merged**
